stages:
  - build
  - deploy_infra

build_nodejs_app:
  stage: build
  script:
    - cd app
    - docker build -t app .
    - docker run -dp 3000:3000 your-node-app
    - curl http://localhost:3000

deploy_infrastructure:
  stage: deploy_infra
  image: hashicorp/terraform:light
  script:
    - cd /roadmap/aws
    - terraform init
    - terraform apply -auto-approve
  dependencies:
    - build_nodejs_app     # Ensures the build job has passed

# deploy_application:
#  stage: deploy_app
#  script:
#    - scp -i deploy_key ./scripts/userdata.sh ubuntu@<EC2_IP>:/tmp/
#    - scp -i deploy_key ./app/* ubuntu@<EC2_IP>:/app/
#    - ssh -i deploy_key ubuntu@<EC2_IP> 'bash /tmp/userdata.sh'
#  dependencies:
#    - deploy_infrastructure 
  only:
    - feature2